export default {
  port: 3000,
  db: 'mongodb://orauckman:jayhawks@ds023613.mlab.com:23613/hps',
  sessionLength: 1800,
  numRandomResults: 12,
  sessionSecret: 'omgwutisthisgoingtobelater',
  stripeTestKey: 'sk_test_zsassPMquDTMHFtrVv4Id1dd',
  defaultProfileImage: 'https://res.cloudinary.com/hps/image/upload/v1513970590/default_df26488a3f216bfdef5569b6c73a9338.png',
  auth: {
    loginFailed: 'login failed, please try again.',
    loginSuccess: 'Login Succeeded',
    minimumRequirements: 'Please enter at minimum a name, username, email, and password to register',
    alreadyInUse: 'That username or email address is already in use',
    generalError: "Whoops! Something didn't work. Please try again",
    registerThanks: 'Thanks for signing up,',
    notAuthenticated: "You can't view this page because you are not logged in",
    loggedOut: 'You are now logged out',
    editNotAuthorized: 'You are not authorized to edit. Please try logging in again.',
    editSuccess: 'Profile Updated Successfully',
    editError: 'There was an error updating your profile. Please try again',
    userDeleted: 'Your account has been deleted',
    deleteError: 'There was an error deleting your account.',
    deleteNotAuthorized: 'You are not authorized to delete that user!',
    couponSuccess: 'Coupon applied successfully',
    couponFailure: 'Invalid Coupon Code',
    cardAddSuccess: 'Card Added Successfully!',
    cardAddFailure: 'There was an issue adding your card, please try again.',
    cardRetrieveError: 'There was an error fetching your credit card info. Please try again.',
    cardDeleteFailure: 'There was an issue removing your card, please try again.',
    cardDeleteSuccess: 'Card successfully removed!',
    cardDefaultFailure: 'There was an issue setting your default card, please try again.',
    cardDefaultSuccess: 'New Default Card Set Successfully!',
    usernameExists: 'The username you selected is already in use. Please choose another one.',
    emailAddressExists: 'The email address you selected is already in use. Please choose another one.'
  },
  errors: {
    userDoesNotExist: 'That user does not exist',
    invalidPassword: 'Invalid password',
    stripeError: 'Something went wrong when processing your payment. Please try again.',
    general: 'Whoops, something went wrong. Please try reloading the page.'
  },
  search: {
    'defineLocation': 'Please Define a location',
    'defineCity': 'You must choose a state with your city',
    'noIndustry': "That industry doesn't exist"
  },
  mail: {
    domain: 'sandboxcacd01660f4146c3a5a13f14280eed4e.mailgun.org',
    key: 'key-07d01e9e401664babc4cff0208d1a583',
    fromAddress: 'Mailgun Sandbox <postmaster@sandboxcacd01660f4146c3a5a13f14280eed4e.mailgun.org>',
    passwordResetSubject: 'Home Party Shows Password Reset Link',
    passwordConfirmSubject: 'Your Home Party Shows Password Has Been Updated',
    success: 'successfully sent email',
    resetRootUrl: 'http://directio.herokuapp.com/reset-password'
  },
  cloudinary: {
    cloud_name: 'hps',
    api_key: '462132641153445',
    api_secret: 'bMjjDCyB9Y9MmmVET2PJR05M8es'
  },
  stateMappings: [
    {text: 'Alabama', value: 'AL'},
    {text: 'Alaska', value: 'AK'},
    {text: 'Arizona', value: 'AZ'},
    {text: 'Arkansas', value: 'AR'},
    {text: 'California', value: 'CA'},
    {text: 'Colorado', value: 'CO'},
    {text: 'Connecticut', value: 'CT'},
    {text: 'Delaware', value: 'DE'},
    {text: 'Florida', value: 'FL'},
    {text: 'Georgia', value: 'GA'},
    {text: 'Hawaii', value: 'HI'},
    {text: 'Idaho', value: 'ID'},
    {text: 'Illinois', value: 'IL'},
    {text: 'Indiana', value: 'IN'},
    {text: 'Iowa', value: 'IA'},
    {text: 'Kansas', value: 'KS'},
    {text: 'Kentucky', value: 'KY'},
    {text: 'Louisiana', value: 'LA'},
    {text: 'Maine', value: 'ME'},
    {text: 'Maryland', value: 'MD'},
    {text: 'Massachusetts', value: 'MA'},
    {text: 'Michigan', value: 'MI'},
    {text: 'Minnesota', value: 'MN'},
    {text: 'Mississippi', value: 'MS'},
    {text: 'Missouri', value: 'MO'},
    {text: 'Montana', value: 'MT'},
    {text: 'Nebraska', value: 'NE'},
    {text: 'Nevada', value: 'NV'},
    {text: 'New Hampshire', value: 'NH'},
    {text: 'New Jersey', value: 'NJ'},
    {text: 'New Mexico', value: 'NM'},
    {text: 'New York', value: 'NY'},
    {text: 'North Carolina', value: 'NC'},
    {text: 'North Dakota', value: 'ND'},
    {text: 'Ohio', value: 'OH'},
    {text: 'Oklahoma', value: 'OK'},
    {text: 'Oregon', value: 'OR'},
    {text: 'Pennsylvania', value: 'PA'},
    {text: 'Rhode Island', value: 'RI'},
    {text: 'South Carolina', value: 'SC'},
    {text: 'South Dakota', value: 'SD'},
    {text: 'Tennessee', value: 'TN'},
    {text: 'Texas', value: 'TX'},
    {text: 'Utah', value: 'UT'},
    {text: 'Vermont', value: 'VT'},
    {text: 'Virginia', value: 'VA'},
    {text: 'Washington', value: 'WA'},
    {text: 'West Virginia', value: 'WV'},
    {text: 'Wisconsin', value: 'WI'},
    {text: 'Wyoming', value: 'WY'}
  ]
}
