// GLOBAL
export const TOGGLE_MENU_TYPE = 'TOGGLE_MENU_TYPE';

// SEARCH
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const TOGGLE_SEARCH_FILTERS = 'TOGGLE_SEARCH_FILTERS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_FILTER_TAB = 'SET_FILTER_TAB';
export const ACTIVATE_CHOSEN_FILTER = 'ACTIVATE_CHOSEN_FILTER';
export const SET_LOADING_STATE = 'SET_LOADING_STATE';
export const SET_RESULTS_STATUS = 'SET_RESULTS_STATUS';
export const HIDE_BASIC_CARDS = 'HIDE_BASIC_CARDS';

// AUTH
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
