// LANDING PAGE
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const UPDATE_STATES = 'UPDATE_STATES';
export const UPDATE_CITIES = 'UPDATE_CITIES';
export const UPDATE_COMPANY_INDUSTRIES = 'UPDATE_COMPANY_INDUSTRIES';

// SIGN UP PROCESS
export const UPDATE_PROGRESS_BAR = 'UPDATE_PROGRESS_BAR';
export const UPDATE_COMPANIES = 'UPDATE_COMPANIES';
export const UPDATE_SIGN_UP_CITIES = 'UPDATE_SIGN_UP_CITIES';
export const UPDATE_SIGN_UP_SELECTED_STATE = 'UPDATE_SIGN_UP_SELECTED_STATE';
export const UPDATE_SIGN_UP_INFO = 'UPDATE_SIGN_UP_INFO';
export const UPDATE_SIGN_UP_STATES = 'UPDATE_SIGN_UP_STATES';

// ACCOUNT PAGES
export const UPDATE_AUTH_STATUS = 'UPDATE_AUTH_STATUS';
export const SET_USER_DATA = 'SET_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_EDIT_INFO = 'UPDATE_EDIT_INFO';
export const UPDATE_USER_AREAS = 'UPDATE_USER_AREAS';
export const UPDATE_EDIT_STATES = 'UPDATE_EDIT_STATES';
export const UPDATE_EDIT_PROGRESS_BAR = 'UPDATE_EDIT_PROGRESS_BAR';
