export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const UPDATE_STATES = 'UPDATE_STATES';
export const UPDATE_CITIES = 'UPDATE_CITIES';
export const UPDATE_COMPANY_INDUSTRIES = 'UPDATE_COMPANY_INDUSTRIES';
